### PR TITLE
Updated go eth and elrd logger

### PR DESCRIPTION
**Pull request by alexandru-calinoiu**
Update eth go client.

### CODE REVIEW

**Comment by alexandru-calinoiu** [comment]
@iulianpascalau I was not able to update `elrond-go` since `elrond-sdk-erdgo` seems to be dependent on an older version

**Review by levelboy — APPROVED** [review]

**Comment by iulianpascalau** [comment]
Will update the sdk asap.

**Review by iulianpascalau — COMMENTED** [review]
erdgo sdk is updated to v1.0.3 -> it uses the elrond-go v1.2.20 version (the upcoming mainnet release) cc @alexandru-calinoiu

**Comment by alexandru-calinoiu** [comment]
I get the following error

```
go: github.com/ElrondNetwork/elrond-go@v1.2.20 requires
	github.com/ElrondNetwork/arwen-wasm-vm/v1_2@v1.2.30: reading github.com/ElrondNetwork/arwen-wasm-vm/v1_2/v1_2/go.mod at revision v1_2/v1.2.30: unknown revision v1_2/v1.2.30
```

**Review by LucianMincu — APPROVED** [review]

**Pull request merged**
